### ISSUE TITLE
Person contact details

### ISSUE THREAD

**Issue by philbarker** [philbarker/transcript_jsonld#6]
Our model provides the address for a student via a Contact object (which allows for contextualizing of the contact), CEDS attaches the address directly to the Person.

Should we use:
- A CTDL ContactPoint
```mermaid
graph LR
   S(Student) -- ceterms:targetContactPoint --> C(ceterms:ContactPoint) -- xyz:address --> A(ceds:Address)
```

- Schema.org ContactPoint
```mermaid
graph LR
   S(Student) -- schema:contactPoint --> C(schema:ContactPoint)  -- xyz:address --> A(ceds:Address)
```

- Create pesc: terms
```mermaid
graph LR
   S(Student) -- pesc:contactPoint --> C(pesc:ContactPoint)  -- xyz:address --> A(ceds:Address)
```

- or adopt the CEDS model:
```mermaid
graph LR
   S(Student) -- ceds:hasPersonAddress --> A(ceds:PersonAddress)
```

**Comment by 4pins** [comment]
I would have done it like CEDS but I'm no RDF expert.  Should we recommend CEDS do it differently?

**Comment by philbarker** [comment]
From meeting today: 
* Contact is used by organization as well as person
* Address data is reusable and could (in principle, in the future) be referenced by id
* Might need different contactTypes for same address for different people
No argument against keeping ContactShape.

Agreement to use CTDL where CEDS does not have coverage.

Therefore:
- keep current model
- use ceterms: properties for contact point

**Comment by philbarker** [comment]
@4pins both are valid in RDF, and schema.org actually allows both. After reflection I prefer using a ContactPoint object because it clarifies the relationship between the person and the address, otherwise it could be a term-time address, permanent residence address, PO box contact or whatever.

**Comment by 4pins** [comment]
Alright.

As long as we are aligning with preexisting things on one side or the other, that is all I can really ask for.
