### ISSUE TITLE
Remove school information from Student shape & add link to Organization

### ISSUE THREAD

**Issue by philbarker** [philbarker/transcript_jsonld#8]
We currently have pesc:organizationName in the StudentShape.
The example data has a "HighSchool" property (with OrgName and CEEBACT,)

Should there be a link from Student shape to Organization indicating the High School attended?

```mermaid
graph LR
P(Student) -- attendedHighSchool --> O(Organization)
```

**Comment by 4pins** [comment]
Organization is one of the keys to CEDS that it is too late for SIF to adjust our model to.  I'd highly recommend trying to align with them here.  This should lead to significantly less pain when building the bridge between secondary and higher education going into the future.

**Comment by philbarker** [comment]
Should be a link to High School as it is information about which high school the student attended.

Need to check how CEDS handles this.

**Comment by 4pins** [comment]
My understanding is in CEDS a High School is an Organization.  While is SIF it is a School.  I think it would be in PESC's best interest to adopt CEDS concept of an Organization.

<img width="1012" alt="Screenshot 2023-10-13 at 11 15 08 AM" src="https://github.com/philbarker/transcript_jsonld/assets/10967355/a2a0493d-6a57-4c63-87e1-ffbb7fd53d0a">

**Comment by aemnathanclinton** [comment]
@philbarker The CEDS Ontology follows the WC3 Organization model, leveraging a "Membership" object to connect a person to an organization for a range in time in a particular role.  

![image](https://github.com/philbarker/transcript_jsonld/assets/27246381/64664ca7-93fe-472d-84a3-6c7106eb109d)

The relationships I think you're looking for are "isMember," "isMemberOf," and "performsRole" in the CEDS Ontology.

**Comment by philbarker** [comment]
Transferred to new repo & closed here.
